#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_INTERNAL_IP:8080
# save as .openshift/action_hooks/start
export HTTP_CLIENT="wget --no-check-certificate -O"
export PORT=$OPENSHIFT_INTERNAL_PORT
export HOST=$OPENSHIFT_INTERNAL_IP
export HOME=$OPENSHIFT_DATA_DIR/home
export LEIN_JVM_OPTS=-Duser.home=$HOME
export APPDIR="vertx-play"
export LEIN_REPL_HOST=$HOST 
echo $OPENSHIFT_DATA_DIR
echo $OPENSHIFT_REPO_DIR
cp $OPENSHIFT_REPO_DIR/misc/profiles.clj $OPENSHIFT_REPO_DIR/../data/home/.lein/
cd $OPENSHIFT_REPO_DIR/diy/$APPDIR
$OPENSHIFT_REPO_DIR/bin/lein deps
$OPENSHIFT_REPO_DIR/bin/lein cljsbuild once
$OPENSHIFT_REPO_DIR/bin/lein vertx run >${OPENSHIFT_DIY_LOG_DIR}/lein.log 2>&1 &
disown
